spring:
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: classpath:application-oauth.yml


app.auth:
  accessTokenSecret: ${ACCESS_TOKEN_SECRET}
  refreshTokenSecret: ${REFRESH_TOKEN_SECRET}
  accessTokenExpiry: 86400000
  refreshTokenExpiry: 604800000
  refreshTokenNearExpiryCriterion: 259200000
