spring:
  security:
    oauth2.client:
      registration:
        kakao:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          client-authentication-method: POST
          authorization-grant-type: authorization_code
          scope:
            - account_email
            - profile_nickname
            - profile_image
          client-name: Kakao
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id

frontend.redirect-uri: http://localhost:3000/login/oauth2/code/kakao
frontend.authorized-redirect-uris: >
  http://localhost:3000/login/oauth2/code/kakao,
  https://swp-9wp56ifkv-softwareproject2022n.vercel.app/login/oauth2/code/kakao